# creation du container docker avec l'agent log insight


FROM photon


COPY ./LIagent.bin /tmp/LIagent.bin


# RUN  tdnf -y update \
RUN  tdnf install -y awk tar gzip \
&&   chmod +x /tmp/LIagent.bin \
&&   /tmp/LIagent.bin \
&&   rm -rf LIagent.bin \
&&   curl -o /home/container_start.sh https://raw.githubusercontent.com/ahugla/LogInsight/master/sidecontainer_with_agent/container_start.sh \
&&   chmod 755 /home/container_start.sh \
&&   tdnf remove -y mpfr gmp gawk tar gzip  # limiter la taille du container (on retire ce qui est installé par awk, tar et gzip)



CMD /home/container_start.sh               # WORKS
# ENTRYPOINT ["/home/container_start.sh"]  # DOES NOT WORK



# USE IT THAT WAY WITH DOCKER
# docker build -t alexfr75/alex-liagent-light:1.0 .
# docker run -d -e "LI_SERVER=1.1.1.300"  -e "LI_VERSION=v4.8.0" -e "TAG_APPLI=alexphp" alexfr75/alex-liagent-light:1.0
# docker run -d -e "LI_SERVER=1.1.1.300"  -e "LI_VERSION=v4.8.0" -e "TAG_APPLI=alexphp" -v /tmp/pod1_log:/var/log  alexfr75/alex-liagent-light:1.0


