# creation du container docker avec l'agent log insight


FROM photon


RUN  tdnf -y update \
&&   tdnf install -y git awk tar gzip \
&&   curl -o /home/container_start.sh https://raw.githubusercontent.com/ahugla/LogInsight/master/sidecontainer_with_agent/container_start.sh \
&&   chmod 755 /home/container_start.sh


CMD /home/container_start.sh               # WORKS
# ENTRYPOINT ["/home/container_start.sh"]  # DOES NOT WORK



# USE IT THAT WAY WITH DOCKER
# docker build -t alexfr75/alex-liagent:1.0 .
# docker run -d -e "LI_SERVER=1.1.1.300"  -e "LI_VERSION=v4.8.0" -e "TAG_APPLI=alexphp" -e "APPLI_LOG_DIR=/var/log/nginx" alexfr75/alex-liagent:1.0
# docker run -d -e "LI_SERVER=1.1.1.300"  -e "LI_VERSION=v4.8.0" -e "TAG_APPLI=alexphp" -e "APPLI_LOG_DIR=/var/log/nginx" -v /tmp/pod1_log:/var/log  alexfr75/alex-liagent:1.0


